# Default values for genesis-docs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

# NOTE: This chart does not use the nested image.repository, image.tag, and
#       image.pullPolicy keys that are created by default when you run `helm create`.
#
#      Instead we use flat imageRepository, imageTag, and imagePullPolicy keys.
#      This is done to make it easy to set the imageTag key to a specific tag
#      (instead of :latest) at release-time using sed.
image:
  pullPolicy: IfNotPresent
  repository: gcr.io/infra-dev-249211/docs
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  name: genesis-docs
  type: ClusterIP
  port: 80
  protocol: TCP
  targetPort: 80
environment:


ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: docs.infra.whiteblock.io
      http:
        paths:
          - path: /
            backend:
              serviceName: genesis-docs
              servicePort: 80
  tls:
    - secretName: genesis-docs-tls
      hosts:
        - docs.infra.whiteblock.io


resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
#   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

secrets: {}
